### ISSUE TITLE
mongo_mapper throws an error with save_with_validation

### ISSUE THREAD

**Issue by bitzesty** [grimen/devise_facebook_connectable#12]
Can this line in authenticate!

```
user.save_with_validation(false)
```

be replaced with:

```
user.save(false)
```

**Comment by bitzesty** [comment]
http://github.com/bitzesty/devise_facebook_connectable/commit/026805056e410f5a027f6699670d33a2a9cf9294

**Comment by grimen** [comment]
Great, will pull it in.

**Comment by grimen** [comment]
Pulled in, closing.
