### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by dbrain** [grimen/devise_facebook_connectable#17]
Hey, sorry for the dumb question but what is the use case for this?
Can I put a facebook connect link on the sign up page and users can use it to log on to my site? (creating a record for them in my database). Or do they need an account for my site that they can then link to facebook?

Thanks!

**Comment by joshk** [comment]
Hi dbrain,

I think this is more of a question then an issue. Try asking this on the devise forums first before logging as issue.

As for how facebook_connectable is used, it can be used as a signup/login mechimism similar to vimeo etc. (click on fb connect button, hey presto you are logged in, meaning a user object has been created for you).

As for the linking part, I am not 100% sure on this, but if in doubt, have a go.

Enjoy,

Josh

**Comment by dbrain** [comment]
Thanks Josh, I didn't realise there was a devise forum.

I have been attempting to use facebook connect (via this plugin, following the instructions) to log in to my application. Currently all it's doing is taking me to the sign up page, and not touching the database.
Asked the dumb question because after a while of playing around I was getting nowhere and had a feeling I was trying to make it do something it wasn't built for.

I'll play around a bit more and hit up the forums. Thanks again!

**Comment by joshk** [comment]
My pleasure, best of luck

**Comment by dbrain** [comment]
Sorry to hassle again, but do you have a link to the 'devise forums' you mentioned?

My issue at the moment is the facebook_link is trying to use the put method against sessions/new (users/sign_in) which isn't a valid method.

**Comment by grimen** [comment]
Sorry,  don't really got enough info to tell what the question really is. Closing, feel free top re-open with additional info.
