### ISSUE TITLE
Devise 1.0.6 breaks facebook_connectable

### ISSUE THREAD

**Issue by mattvanhorn** [grimen/devise_facebook_connectable#19]
There is no longer an 'authenticatable(routes, mapping)' method.
It is now 'devise_session(mapping, controllers)' and the alias in routes.rb blowed up.

**Comment by grimen** [comment]
Fixed Devise 1.0.6 compatibility. Closed by 54cc05329d673a1ceb4d0e3f6db1979a83dbbda3

**Comment by ykameshrao** [comment]
Thanks a lot grimen. Thank you mattvanhorn too.
