### ISSUE TITLE
rails 3.0.0-beta3 and devise 1.1.rc1

### ISSUE THREAD

**Issue by halo** [grimen/devise_facebook_connectable#20]
I looked through all issues but didn't find anyone else having this problem. I'm trying to get devise_facebook_connectable working with the most recent versions (as well as a facebooker fork which will work in rails 3: http://github.com/joren/facebooker ).

I sent you a pull request for http://github.com/funkensturm/devise_facebook_connectable/commit/067b10c760eb088b44c61b209caa371912b32b6a to continue trying to make this run :)

**Comment by mryan43** [comment]
I think and integration of facebooker2 into devise from scratch would be less painfull and better for the future of this project.

The author of facebooker said he won't update it for rails 3, in favor of facebooker2 and mogli.

**Comment by grimen** [comment]
Yes, or mini_fb - more low-level. If I get time to work on this that would be my call. Haven't looked much at facebooker2 yet.
