### ISSUE TITLE
facebook.yml callback_url has wacky side effects

### ISSUE THREAD

**Issue by levity** [grimen/devise_facebook_connectable#27]
When I set callback_url under facebook.yml, in the development section...

```
development:
    <<: *defaults
    callback_url: http://mydevserver:3000
```

...that hostname is prepended to all my CSS and JS includes!

devise_facebook_connectable 0.2.2, rails 2.3.8.

**Comment by grimen** [comment]
This plugin is not maintained anymore, sorry. =/
