### ISSUE TITLE
Problem signing out with facebooker 1.0.75

### ISSUE THREAD

**Issue by bilditup1** [grimen/devise_facebook_connectable#28]
Hi-
Signing out doesn't work with the latest -v of facebooker: the 'signing-out' pop-up comes up, and on page-reload, a message flashed that the user is signed out, but the user is still signed-in in the corner (e.g. there's still a facebook signout link). Is the user getting autologged back in to fb somehow? I reverted back to 1.0.74 for the time being.
I'm running the new ruby1.9.2-p0 on WinXP with Rails 2.3.8.

**Comment by bilditup1** [comment]
and of course, d_f_c-0.2.2

**Comment by grimen** [comment]
Sorry, I seriously got no clue as I haven't worked on this for many months and don't maintain it anymore and neither will in the future I'm quite sure. Facebook got a new API. Try implement using MiniFB + Devise maybe.
